// Login Actions
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_RESPONSE = "LOGIN_RESPONSE"
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR"
export const SET_LOGIN_USER = "SET_LOGIN_USER"
export const CLEAR_LOGIN_ERROR = "CLEAR_LOGIN_ERROR"
export const LOGOUT_USER = "LOGOUT_USER"

// Register Action
export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_RESPONSE = "REGISTER_RESPONSE"
export const SET_REGISTER_ERROR = "SET_REGISTER_ERROR"
export const CLEAR_REGISTER_ERROR = "CLEAR_REGISTER_ERROR"

